config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  
  root 'static_assets#home'

  get '/stage', to: 'static_assets#stage'
  get '/teststage', to: 'static_assets#teststage'


  get '/stages/one', to: 'stages#one'
  get '/stages/two', to: 'stages#two'

  resources :static_assets



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stage.rb
class Stage < ApplicationRecord
end

app/models/static_asset.rb
class StaticAsset < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
end

app/controllers/static_assets_controller.rb
class StaticAssetsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/helpers/static_assets_helper.rb
module StaticAssetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

  	<!-- Google Font Import -->
  	 <link href="https://fonts.googleapis.com/css?family=Russo+One" rel="stylesheet">  

    <title>JustIn</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stages/one.html.erb
<div id="arena">

	<div id="box" style="position: absolute; top: 10px; left: 10px; height: 50px; width: 50px; background-color: red;"></div>

	<div id="contenDisplay" style="position: absolute; height: 12vh; width: 16vw; top: 87vh; left: 83vw; background-color: rgba(0,0,0,0.8); color: white;">
		<div style="width:100%; height: 100%; position: relative; padding-left: 10px; padding-top: 10px;">
		
			<span id="fps_display">
				sspan
			</span>
			</br></br>
			Pressed: <span id="button_display">
				span
			</span>


		</div>


	</div>

</div>


<style>

	* {
		box-sizing: border-box;
	}
	

	body {
		box-sizing: border-box;
	    height: 100vh;
	    width: 100vw;
 		margin: 0px 0px 0px 0px;
 	    color: black;
	}

	#arena {
		width: 100%;
		height: 100%;
	}

	#box {
	    background-color: red;
	    height: 50px;
	    left: 150px;
	    position: absolute;
	    top: 10px;
	    width: 50px;
	}


</style>


<script>







	document.addEventListener('keydown', function(ev) { return onkey(ev, ev.keyCode, true);  }, false, { once: true });
	document.addEventListener('keyup',   function(ev) { return onkey(ev, ev.keyCode, false); }, false, { once: true });


	var right_keydown = false;
	var left_keydown = false;
	var up_keydown = false; 
	var down_keydown = false; 
	var space_keydown = false; 
	var d_keydown = false;
	var a_keydown = false;
	var w_keydown = false; 
	var s_keydown = false; 

	var prev_right_keydown = false;
	var prev_left_keydown = false;
	var prev_up_keydown = false; 
	var prev_down_keydown = false; 
	var prev_space_keydown = false; 
	var prev_d_keydown = false;
	var prev_a_keydown = false;
	var prev_w_keydown = false; 
	var prev_s_keydown = false; 

	var keypress_summary = '';

	var KEY = {

	    BACKSPACE: 8,
	    TAB:       9,
	    RETURN:   13,
	    ESC:      27,
	    SPACE:    32,
	    PAGEUP:   33,
	    PAGEDOWN: 34,
	    END:      35,
	    HOME:     36,
	    LEFT:     37,
	    UP:       38,
	    RIGHT:    39,
	    DOWN:     40,
	    INSERT:   45,
	    DELETE:   46,
	    ZERO:     48, ONE: 49, TWO: 50, THREE: 51, FOUR: 52, FIVE: 53, SIX: 54, SEVEN: 55, EIGHT: 56, NINE: 57,
	    A:        65, B: 66, C: 67, D: 68, E: 69, F: 70, G: 71, H: 72, I: 73, J: 74, K: 75, L: 76, M: 77, N: 78, O: 79, P: 80, Q: 81, R: 82, S: 83, T: 84, U: 85, V: 86, W: 87, X: 88, Y: 89, Z: 90,
	    TILDA:    192
	
	};


	function onkey(ev, key, pressed) {




  	  console.log('KEYPRESS LOG: ' + String(key));



	  switch(key) {




	  	case KEY.W:  
	    	if(pressed && w_keydown) {
	    		w_keydown = true;
	    		prev_w_keydown = true;
	    	} else if (pressed) {
	    		w_keydown = true;
				prev_w_keydown = false;	    	
			} else {
				w_keydown = false;
				prev_w_keydown = false;
			};
	    	ev.preventDefault();
	    break;

	    case KEY.S:
	    	if(pressed && s_keydown) {
	    		s_keydown = true;
	    		prev_s_keydown = true;
	    	} else if (pressed) {
	    		s_keydown = true;
	    		prev_s_keydown = false;
	    	} else {
	    		s_keydown = false;
	    		prev_s_keydown = false;
	    	};
	    	ev.preventDefault();
	    break;

	    case KEY.A:  
	    	if(pressed && a_keydown) {
	    		a_keydown = true;
	    		prev_a_keydown = true;
	    	} else if (pressed) {
	    		a_keydown = true;
				prev_a_keydown = false;	    	
			} else {
				a_keydown = false;
				prev_a_keydown = false;
			};
	    	ev.preventDefault();
	    break;

	    case KEY.D:
	    	if(pressed && d_keydown) {
	    		d_keydown = true;
	    		prev_d_keydown = true;
	    	} else if (pressed) {
	    		d_keydown = true;
	    		prev_d_keydown = false;
	    	} else {
	    		d_keydown = false;
	    		prev_d_keydown = false;
	    	};
	    	ev.preventDefault();
	    break;

	    case KEY.UP:  
	    	if(pressed && up_keydown) {
	    		up_keydown = true;
	    		prev_up_keydown = true;
	    	} else if (pressed) {
	    		up_keydown = true;
				prev_up_keydown = false;	    	
			} else {
				up_keydown = false;
				prev_up_keydown = false;
			};
	    	ev.preventDefault();
	    break;

	    case KEY.DOWN:
	    	if(pressed && down_keydown) {
	    		down_keydown = true;
	    		prev_down_keydown = true;
	    	} else if (pressed) {
	    		down_keydown = true;
	    		prev_down_keydown = false;
	    	} else {
	    		down_keydown = false;
	    		prev_down_keydown = false;
	    	};
	    	ev.preventDefault();
	    break;

	    case KEY.LEFT:  
	    	if(pressed && left_keydown) {
	    		left_keydown = true;
	    		prev_left_keydown = true;
	    	} else if (pressed) {
	    		left_keydown = true;
				prev_left_keydown = false;	    	
			} else {
				left_keydown = false;
				prev_left_keydown = false;
			};
	    	ev.preventDefault();
	    break;

	    case KEY.RIGHT:
	    	if(pressed && right_keydown) {
	    		right_keydown = true;
	    		prev_right_keydown = true;
	    	} else if (pressed) {
	    		right_keydown = true;
	    		prev_right_keydown = false;
	    	} else {
	    		right_keydown = false;
	    		prev_right_keydown = false;
	    	};
	    	ev.preventDefault();
	    break;

	    case KEY.SPACE: 
	    	if (pressed && space_keydown) {
	    		space_keydown = true;
	    		prev_space_keydown = true;
	    	} else if (pressed) {
	    		space_keydown = true;
	    		prev_space_keydown = false;
	    	} else {
	    		space_keydown = false;
	    		prev_space_keydown = false;
	    	};
	    	ev.preventDefault();
	    break;

	  };
	};



	
	var box = document.getElementById('box'),
        contenDisplay = document.getElementById('contenDisplay'),
        fpsDisplay = document.getElementById('fps_display'),
        buttonDisplay = document.getElementById('button_display'),

    box_X_Pos = 10,
    box_X_LastPos = 10,
    box_Y_Pos = 10,
    box_Y_LastPos = 10,

    boxVelocity = 0.15,

    upVector = 0,
    leftVector = 0,
    downVector = 0,
    rightVector = 0,

    window_X_limit = (window.innerWidth - 50); //Right Edge of Arena
    window_Y_limit = (window.innerHeight - 50); //Bottom Edge of Arena

    lastFrameTimeMs = 0,
    maxFPS = 60,
    timestep = 1000 / 60,
    fps = 60,
    framesThisSecond = 0,
    lastFpsUpdate = 0,    

    delta = 0,

    running = false,
    started = false,
    frameID = 0;






	function update(delta) {




	    if (space_keydown && !prev_space_keydown) {
	    	prev_space_keydown = true;
	    	boxVelocity = -boxVelocity;
	    };


	   	box_X_LastPos = box_X_Pos;
	   	if (d_keydown) {

	   		box_X_Pos += boxVelocity * delta;

	   	} else if (a_keydown) {

	   		box_X_Pos -= boxVelocity * delta;
	   	};
	    

	   	box_Y_LastPos = box_Y_Pos;
	  	if (s_keydown) {

	   		box_Y_Pos += boxVelocity * delta;

	   	} else if (w_keydown) {

	   		box_Y_Pos -= boxVelocity * delta;
	   	};








	    if (up_keydown) {
	    	if (boxVelocity > 0) {
	    		boxVelocity += 0.002;
	    	} else if (boxVelocity < 0) {
	    		boxVelocity += -0.002;
	    	} else {
	    		//Nothing Here
	    	};
	    }; 

	    if (down_keydown) {
	    	if (boxVelocity > 0) {
	    		boxVelocity += -0.002;
	    	} else if (boxVelocity < 0) {
	    		boxVelocity += 0.002;
	    	} else {
	    		//Nothing Here
	    	};
	    };

	    // Switch directions if we go too far to the right or left
	    if (box_X_Pos >= window_X_limit || box_X_Pos <= 0) boxVelocity = -boxVelocity;


	    // Switch directions if we go too far to far up or down
	    if (box_Y_Pos >= window_Y_limit || box_Y_Pos <= 0) boxVelocity = -boxVelocity;


	}

	function draw(interp) {

	    box.style.left = (box_X_LastPos + (box_X_Pos - box_X_LastPos) * interp) + 'px';
	    box.style.top = (box_Y_LastPos + (box_Y_Pos - box_Y_LastPos) * interp) + 'px';



	    fpsDisplay.textContent = Math.round(fps) + ' FPS';


	    keypress_summary = '';
	    
	    if (right_keydown) {
	    	keypress_summary += "{#RIGHT}";
	    };

	    if (left_keydown) {
	    	keypress_summary += "{#LEFT}";
	    };

	    if (up_keydown) {
	    	keypress_summary += "{#UP}";
	    };

	    if (down_keydown) {
	    	keypress_summary += "{#DOWN}";
	    };

	    if (space_keydown) {
	    	keypress_summary += "{#SPACE}";
	    };
	    
	    if (d_keydown) {
	    	keypress_summary += "{ D }";
	    };

	    if (a_keydown) {
	    	keypress_summary += "{ A }";
	    };

	    if (w_keydown) {
	    	keypress_summary += "{ W }";
	    };

	    if (s_keydown) {
	    	keypress_summary += "{ S }";
	    };


	    buttonDisplay.textContent = String(keypress_summary);


	    if (space_keydown) {
	    	fpsDisplay.textContent = 'space';
	    };

	}

















	function panic() {
	    delta = 0;
	}

	function begin() {
	}

	function end(fps) {
	    if (fps < 25) {
	        box.style.backgroundColor = 'black';
	    }
	    else if (fps > 30) {
	        box.style.backgroundColor = 'red';
	    }
	}

	function stop() {
	    running = false;
	    started = false;
	    cancelAnimationFrame(frameID);
	}

	function start() {
	    if (!started) {
	        started = true;
	        frameID = requestAnimationFrame(function(timestamp) {
	            draw(1);
	            running = true;
	            lastFrameTimeMs = timestamp;
	            lastFpsUpdate = timestamp;
	            framesThisSecond = 0;
	            frameID = requestAnimationFrame(mainLoop);
	        });
	    }
	}

	function mainLoop(timestamp) {
	    // Throttle the frame rate.    
	    if (timestamp < lastFrameTimeMs + (1000 / maxFPS)) {
	        frameID = requestAnimationFrame(mainLoop);
	        return;
	    }
	    delta += timestamp - lastFrameTimeMs;
	    lastFrameTimeMs = timestamp;

	    begin(timestamp, delta);

	    if (timestamp > lastFpsUpdate + 1000) {
	        fps = 0.25 * framesThisSecond + 0.75 * fps;

	        lastFpsUpdate = timestamp;
	        framesThisSecond = 0;
	    }
	    framesThisSecond++;

	    var numUpdateSteps = 0;
	    while (delta >= timestep) {
	        update(timestep);
	        delta -= timestep;
	        if (++numUpdateSteps >= 240) {
	            panic();
	            break;
	        }
	    }

	    draw(delta / timestep);

	    end(fps);

	    frameID = requestAnimationFrame(mainLoop);
	}

	start();
	
</script>

app/views/stages/two.html.erb
<h1>Testing Animations</h1>






<h3 style="text-align: center;">Animation #1: <b>Hungry Monster</b></h3>
<div class="monster">
	
</div>


</br></br>

<h3 style="text-align: center;">Animation #2: <b>Assasin</b></h3>
<div class="character">
	
</div>

<style>

	body {

	}

	.monster {
	  width: 190px;
	  height: 240px;
	  margin: 2% auto;
	  background: url('https://treehouse-code-samples.s3.amazonaws.com/CSS-DD/codepen/blog/monster.png') left center;
	  animation: play .8s steps(10) infinite;
	}

	@keyframes play {
		100% { background-position: -1900px; }
	}



	<% temp_string = request.original_url %>
	<% temp_string.slice!(request.fullpath) %>

	.character {
		width: 258px;
		height: 220px;
		margin: 2% auto;
		border: solid black;
		background: <%= "url('".html_safe + temp_string + asset_path('johnny/survivor-move_animated.png') + "') left center".html_safe %>;

	  	animation: second_play .8s steps(20) infinite;
	}


	@keyframes second_play {
		100% { background-position: -5160px; }
	}

</style>

app/views/static_assets/home.html.erb
<div id="container">

	<div id="header">
		JUSTIN's GAME NAME
	</div>


	<div id="main">
		
		<div id="embedded_container" style="width: 100%;height: 100%;">

			<div id="embedded_menu" style="height: 100%; width: 100%; padding: 8px 16px 8px 16px;">
				
				<span style="font-size: 1.3em;">This is the first template for your game. There is not much here yet, and eveything that is here will likely be replaced soon to forever be forgotten. More so a temporary template</span>
				</br>
				</br>
				</br>

				<%= link_to(stage_path, {:style => "width: 100px; height: 3em;", :class => "jobheader_wrap"} ) do %>
					<div style="width: 40%; margin-left: 30%; height: 40px; text-align: center; padding-top: 1em; background-color: white;">
						Start Game
					</div>
				<% end %>

				</br>

				<%= link_to(teststage_path, {:style => "width: 100px; height: 3em;", :class => "jobheader_wrap"} ) do %>
					<div style="width: 40%; margin-left: 30%; height: 40px; text-align: center; padding-top: 1em; background-color: white;">
						Test Stage
					</div>
				<% end %>

				</br>

				<%= link_to(stages_one_path, {:style => "width: 100px; height: 3em;", :class => "jobheader_wrap"} ) do %>
					<div style="width: 40%; margin-left: 30%; height: 40px; text-align: center; padding-top: 1em; background-color: white;">
						Stage #1
					</div>
				<% end %>

				</br>

				<%= link_to(stages_two_path, {:style => "width: 100px; height: 3em;", :class => "jobheader_wrap"} ) do %>
					<div style="width: 40%; margin-left: 30%; height: 40px; text-align: center; padding-top: 1em; background-color: white;">
						Stage #2
					</div>
				<% end %>


				
			</div>

			
		</div>



	</div>

	<div id="footer" style="text-align: center;padding-top: 15px;">
		Version # | Bitbucket | Heroku | Google | Terms | Privacy
	</div>


</div>



<style>




	html { 

		background-image:
        linear-gradient(rgba(0, 0, 0, 0.65), rgba(0, 0, 0, 0.65)), 
        url('https://media.giphy.com/media/3oFzmdMmI6iW7JN1p6/giphy-downsized-large.gif');


        font-family: 'Russo One', sans-serif;

	  	background-size: cover;
	}

	body {
	    height: 100vh;
	    width: 100vw;
 		margin: 0px 0px 0px 0px;
 	    color: white;
	}





	#container {

		display: grid;
		width: 100%;
		height: 100%;
		grid-template-columns: 20% 20% 20% 20% 20%;
		grid-template-rows: 14% 81% 5%;

	}

	#header {

		margin-top: 4vh;
		margin-left: 8%; 
		grid-column-start: 1;
		grid-column-end: 6;
		grid-row-start: 1;
		grid-row-end: 2;

		color: DarkKhaki;

		font-size: 3em;

	}

	#main {
		grid-column-start: 1;
		grid-column-end: 6;
		grid-row-start: 2;
		grid-row-end: 3;

		color: black;
	}

	#footer {

		grid-column-start: 1;
		grid-column-end: 6;
		grid-row-start: 3;
		grid-row-end: 4;

		background-color: rgba(255,255,255,0.6);

		color: black;

	}

	#embedded_container {
		display: grid;
		grid-template-columns: 30% 40% 30%;
		grid-template-rows: 20% 60% 20%;
	}

	#embedded_menu {
		grid-column-start: 2;
		grid-column-end: 3;
		grid-row-start: 2;
		grid-row-end: 3;
		background-color: rgba(189,183,107,0.8);
	}
	









</style>

app/views/static_assets/stage.html.erb
<div id="arena">

	<div id="box" style="position: absolute; top: 10px; left: 10px; height: 50px; width: 50px; background-color: red;"></div>

	<div id="fpsDisplay" style="position: absolute; top: 70px; left: 10px;"></div>
	</div>


<style>
	

	body {
	    height: 100vh;
	    width: 100vw;
 		margin: 0px 0px 0px 0px;
 	    color: black;
	}

	#arena {
		width: 100%;
		height: 100%;
	}

	#box {
	    background-color: red;
	    height: 50px;
	    left: 150px;
	    position: absolute;
	    top: 10px;
	    width: 50px;
	}


</style>


<script>
	
	var box = document.getElementById('box'),
    fpsDisplay = document.getElementById('fpsDisplay'),
    boxPos = 10,
    boxLastPos = 10,
    boxVelocity = 0.08,
    limit = 500,
    lastFrameTimeMs = 0,
    maxFPS = 60,
    delta = 0,
    timestep = 1000 / 60,
    fps = 60,
    framesThisSecond = 0,
    lastFpsUpdate = 0,
    running = false,
    started = false,
    frameID = 0;

	function update(delta) {
	    boxLastPos = boxPos;
	    boxPos += boxVelocity * delta;
	    // Switch directions if we go too far
	    if (boxPos >= limit || boxPos <= 0) boxVelocity = -boxVelocity;
	}

	function draw(interp) {
	    box.style.left = (boxLastPos + (boxPos - boxLastPos) * interp) + 'px';
	    fpsDisplay.textContent = Math.round(fps) + ' FPS';
	}

	function panic() {
	    delta = 0;
	}

	function begin() {
	}

	function end(fps) {
	    if (fps < 25) {
	        box.style.backgroundColor = 'black';
	    }
	    else if (fps > 30) {
	        box.style.backgroundColor = 'red';
	    }
	}

	function stop() {
	    running = false;
	    started = false;
	    cancelAnimationFrame(frameID);
	}

	function start() {
	    if (!started) {
	        started = true;
	        frameID = requestAnimationFrame(function(timestamp) {
	            draw(1);
	            running = true;
	            lastFrameTimeMs = timestamp;
	            lastFpsUpdate = timestamp;
	            framesThisSecond = 0;
	            frameID = requestAnimationFrame(mainLoop);
	        });
	    }
	}

	function mainLoop(timestamp) {
	    // Throttle the frame rate.    
	    if (timestamp < lastFrameTimeMs + (1000 / maxFPS)) {
	        frameID = requestAnimationFrame(mainLoop);
	        return;
	    }
	    delta += timestamp - lastFrameTimeMs;
	    lastFrameTimeMs = timestamp;

	    begin(timestamp, delta);

	    if (timestamp > lastFpsUpdate + 1000) {
	        fps = 0.25 * framesThisSecond + 0.75 * fps;

	        lastFpsUpdate = timestamp;
	        framesThisSecond = 0;
	    }
	    framesThisSecond++;

	    var numUpdateSteps = 0;
	    while (delta >= timestep) {
	        update(timestep);
	        delta -= timestep;
	        if (++numUpdateSteps >= 240) {
	            panic();
	            break;
	        }
	    }

	    draw(delta / timestep);

	    end(fps);

	    frameID = requestAnimationFrame(mainLoop);
	}

	start();
	
</script>